spring:
  datasource:
    username: root
    password: 1597
    url: jdbc:mysql:///store
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.tingfeng.store.entity,com.tingfeng.store.vo

server:
  port: 8080

user.address.max-count: 20
